### ISSUE TITLE
from syncsweptsine import SyncSeep File "/home/rob/.local/lib/python2.7/site-packages/syncsweptsine.py" line 1121 f'Give 'length'{length} must not be bigger than {maxlengh}.'

### ISSUE THREAD

**Issue by dbdxnuliba** [SiggiGue/syncsweptsine#1]
from syncsweptsine import SyncSeep
File "/home/rob/.local/lib/python2.7/site-packages/syncsweptsine.py" line 1121
f'Give 'length'{length} must not be bigger than {maxlengh}.'
syntaxError: invalid syntax

**Comment by SiggiGue** [comment]
Python 2.7 is not supported.
